### ISSUE TITLE
Add licence information

### ISSUE THREAD

**Issue by Tpt** [pagesjaunes/spacy-french-models#2]
It would be great if this model could be put under a free licence in order to be reusable in legally safe way.

**Comment by thomasgirault** [comment]
The models have been trained with the [French Universal Dependency Corpus](https://github.com/UniversalDependencies/UD_French) which has a [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/) licence. So I guess the same licence is also applicable to the models.

**Comment by Tpt** [comment]
Thank you! I have just made a pull request to add it to the repository README
